resources:
- primeGenerator-service.yaml
- primeGenerator-deployment.yaml
images:
- name: primeGeneratorImage
  newName: ghcr.io/bproforigoss/primegenerator
  newTag: first
configMapGenerator:
- envs:
  - env/chatbot.env
  name: primeGenerator-configmap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 1
  name: primeGenerator-deployment
