resources:
- primeGenerator-service.yaml
- primeGenerator-deployment.yaml
- primeGenerator-servicemonitor.yaml
- primeGenerator-autoscaler.yaml
images:
- name: primegeneratorimage
  newName: ghcr.io/bproforigoss/primegenerator
  newTag: sha-bdd87a6
configMapGenerator:
- envs:
  - env/chatbot.env
  name: primegenerator-configmap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
