resources:
- primeGenerator-service.yaml
- primeGenerator-deployment.yaml
images:
- name: primegeneratorimage
  newName: ghcr.io/bproforigoss/primegenerator
  newTag: sha-e3e9949
configMapGenerator:
- envs:
  - env/chatbot.env
  name: primegenerator-configmap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 1
  name: primegenerator-deployment
