resources:
- primeGenerator-service.yaml
- primeGenerator-deployment.yaml
- primeGenerator-servicemonitor.yaml
images:
- name: primegeneratorimage
  newName: ghcr.io/bproforigoss/primegenerator
  newTag: sha-1f81260
configMapGenerator:
- envs:
  - env/chatbot.env
  name: primegenerator-configmap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 3
  name: primegenerator-deployment
