apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: primegenerator
spec:
  endpoints:
  - interval: 15s
    targetPort: 8080
  selector:
    matchLabels:
      app: primegenerator
