apiVersion: apps/v1
kind: Deployment
metadata:
  name: primegenerator-deployment
  labels:
    app: primegenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primegenerator
  template:
    metadata:
      labels:
        app: primegenerator
    spec:
      containers:
      - name: primegenerator
        image: primegeneratorimage
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: primegenerator-configmap
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080

        
        
          
         
    
      
    
      
