name: set_replica_count_by_chatbot

on: workflow_dispatch
    #inputs:
      #chatID:
        #description: 'Telegram chatID'     
        #required: true

env:
  AGE_KEY: ${{ secrets.AGE_KEY }}
  SOPS_AGE_KEY_FILE: .config/sops/age/keys.txt
             
jobs:
          
  #sending_response_to_chat:
    #runs-on: ubuntu-latest
    #needs: deploy_to_kubernetes_cluster
    
    #steps:
      #- name: Checkout repository
        #uses: actions/checkout@v2
          
      #- name: run chatbot Api
        #run: |
          #curl POST \
          #-H 'Content-Type: application/json' \
          #https://kemadaxbot.bprof.gesz.dev/responseAPI \
          #-d '{"chat_id":"${{github.event.inputs.chatID}}"}'  

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBE_CONFIG}}
               
      - name: Set up Mozilla SOPS 
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
          sudo dpkg -i sops_3.7.1_amd64.deb

        
      - name: Decryption 
        run: |
          ls -a .
          echo "$AGE_KEY" > .config/sops/age/keys.txt
          sops -d  kubernetes/chatbot-app/base/secret/chatbot.enc.env > kubernetes/chatbot-app/base/secret/chatbot.secret
  
          
      - name: Set replicas
        run: |
          cd kubernetes/chatbot-app/base/
          kustomize edit set replicas kemadaxbot-deployment=5
          
          

          
