name: Deploy

on: 
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image tag'     
        required: true
        default: 'sha-adc59d9'
      kubeconfig:     
        required: false
        default: ${{ secrets.KUBE_CONFIG }} 
        
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      kubeconfig:
        required: true   
    

jobs:

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ github.event.inputs.image_name }} 
          
      - name: Deploy to Cluster
        run: |
          export IMG=ghcr.io/bproforigoss/kemadaxbot:${{ github.event.inputs.image_name }}
          envsubst < kemadaxbot-deployment.yaml | kubectl apply -f -
