name: Deploy_debug

on: 

  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      kube_config:
        required: true
      telegram_token:
        required: true
    
jobs:

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.kube_config}}
          
      - name: Deploy to Cluster
        run: |
          cd k8s
          kubectl apply -k edit set image ${{inputs.image_name  }}
          kubectl apply -k ./kubernetes/chatbot-app/overlays/development/
      
          
      
          
