name: Deploy_debug

on: 

  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      kube_config:
        required: true
      telegram_token:
        required: true
    
jobs:

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.kube_config}}
          
      - name: Deploy to Cluster
        run: |
          cd kubernetes/chatbot-app/base/
          kustomize edit set image kemadax=${{inputs.image_name  }}
          cd kubernetes/chatbot-app/base/overlays/development/secrets/
          echo -n ${{secrets.kube_config}} | base64>secrets.txt
          cd kubernetes/chatbot-app/base/overlays/development/
          kubectl kustomize ./
          kubectl apply -k ./
      
          
      
          
