name: Deploy

on: 
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'     
        required: true
      
        
jobs:

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBE_CONFIG}}
          
      - name: Deploy to Cluster
        run: |
          cd kubernetes/chatbot-app/base/
          kustomize edit set image kemadax=${{inputs.image_name  }}
          cd ../../../
          echo -n ${{secrets.TELEGRAM_TOKEN}} > kubernetes/chatbot-app/base/secrets/API_TOKEN
          kubectl apply -k kubernetes/chatbot-app/overlays/production/
          
