name: Deploy

on: 
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'     
        required: true
env:
  AGE_KEY: ${{ secrets.AGE_KEY }}
  SOPS_AGE_KEY_FILE: .config/sops/age/keys.txt
jobs:


  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBE_CONFIG}}
               
      - name: Set up Mozilla SOPS 
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
          sudo dpkg -i sops_3.7.1_amd64.deb

        
      - name: Decryption 
        run: |
          ls -a .
          echo "$AGE_KEY" > .config/sops/age/keys.txt
          sops -d  kubernetes/chatbot-app/base/secret/chatbot.enc.env > kubernetes/chatbot-app/base/secret/chatbot.secret
  
          
      - name: Deploy to Cluster
        run: |
          cd kubernetes/chatbot-app/base/
          kustomize edit set image kemadax=${{github.event.inputs.image_name}}
          cd ../../../
          kubectl apply -k kubernetes/chatbot-app/overlays/production/
          
          
          git config --global user.name 'Automated CI/CD Agent'
          git config --global user.email 'kemadax@gmail.com'
          git commit -am "Chatbot deploys"
          git push
