name: Deploy

on: 
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'     
        required: true
        
  #workflow_call:
    #inputs:
     # image_name:
      #  required: true
      #  type: string
   # secrets:
     # KUBE_CONFIG:
     #   required: true   
    
jobs:

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBE_CONFIG}}
          
      - name: Deploy to Cluster
        run: |
          export IMG=${{github.event.inputs.image_name }}
          envsubst < kemadaxbot-deployment.yaml | kubectl apply -f -
