name: Deploy_debug

on: 

  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      kube_config:
        required: true
      telegram_token:
        required: true
    
jobs:

  deploy_to_kubernetes_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.kube_config}}
          
      - name: Deploy to Cluster
        run: |
          export IMG=${{inputs.image_name }}
          envsubst < kemadaxbot-debug-deployment.yaml | kubectl apply -f -
          
      - name: Deploy service to Cluster
        run: |
          kubectl apply -f kemadaxbot-service.yaml
       
      - name: Deploy secret to Cluster
        run: |
          export SCT= echo -n ${{secrets.telegram_token}} | base64
          kubectl apply -f kemadaxbot-configmap.yaml
          
      - name: Deploy configmap to Cluster
        run: |
          kubectl apply -f kemadaxbot-configmap.yaml
          
      
          
