name: Pipeline

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
permissions: read-all|write-all

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build 
  
  docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
             
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
         
        
  deploy_by_tag:  
        if: ${{ contains(github.ref_name,'deploy')}}
        uses: bproforigoss/kemadaxbot/.github/workflows/deploy.yaml@main
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/kemadaxbot:sha-${GITHUB_SHA::7}
        
        
        #runs-on: ubuntu-latest
        #needs: docker
        #env:
        #  TOKEN: ${{ secrets.REPO_DISPATCH_PAT}}
        #steps:
        #- uses: actions/checkout@v2

        #- name: run Api
         # run: |
          #  curl -u ":$TOKEN" \
           # -X POST \
            #-H "Accept: application/vnd.github.v3+json" \
            #https://api.github.com/repos/bproforigoss/kemadaxbot/actions/workflows/deploy.yaml/dispatches \
           # -d '{"ref": "main", 
            #     "inputs": {
             #       "image_name": "ghcr.io/${{ github.repository_owner }}/kemadaxbot:sha-${GITHUB_SHA::7}"
             #       }
           # }'
        
          
      
