apiVersion: apps/v1
kind: Deployment
metadata:
  name: kemadaxbot-deployment
  labels:
    app: kemadaxbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kemadaxbot
  template:
    metadata:
      labels:
        app: kemadaxbot
    spec:
      containers:
      - name: kemadaxbot
        image: kemadax
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /config/
        - name: secret
          mountPath: /secret/
        env:
        - name: API_TOKEN
          valueFrom: 
            secretKeyRef: 
              key: secrets.txt
              name: kemadaxbot-secret
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: kemadaxbot-configmap
              key: user
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: kemadaxbot-configmap
              key: public_url
      volumes:
      - name: config
        configMap:
          name: kemadaxbot-configmap
      - name: telegram_token
        secret:
          secretName: kemadaxbot-secret
        
        
          
         
    
      
    
      
