apiVersion: apps/v1
kind: Deployment
metadata:
  name: kemadaxbot-deployment
  labels:
    app: kemadaxbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kemadaxbot
  template:
    metadata:
      labels:
        app: kemadaxbot
    spec:
      containers:
      - name: kemadaxbot
        image: kemadax
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: kemadaxbot-configmap
        - secretRef:
              name: kemadaxbot-secret
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080

        
        
          
         
    
      
    
      
