apiVersion: apps/v1
kind: Deployment
metadata:
  name: kemadaxbot-deployment
  labels:
    app: kemadaxbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kemadaxbot
  template:
    metadata:
      labels:
        app: kemadaxbot
    spec:
      containers:
      - name: kemadaxbot
        image: kemadax
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /config/
        - name: secret
          mountPath: /secret/
        envFrom:
        - configMapRef:
            name: kemadaxbot-configmap
        - secretRef:
              name: kemadaxbot-secret
      volumes:
      - name: config
        configMap:
          name: kemadaxbot-configmap
      - name: secret
        secret:
          secretName: kemadaxbot-secret
        
        
          
         
    
      
    
      
