resources:
- kemadaxbot-service.yaml
- kemadaxbot-deployment.yaml
- kemadaxbot-servicemonitor.yaml
- prometheus-role.yaml
- prometheus-rolebinding.yaml
images:
- name: kemadax
  newName: ghcr.io/bproforigoss/kemadaxbot
  newTag: sha-3882523
configMapGenerator:
- envs:
  - env/chatbot.env
  name: kemadaxbot-configmap
secretGenerator:
- envs:
  - secret/chatbot.secret
  name: kemadaxbot-secret
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 1
  name: kemadaxbot-deployment
