resources:
  - kemadaxbot-service.yaml
  - kemadaxbot-deployment.yaml
images:
- name: kemadax
  newName: ghcr.io/bproforigoss/kemadaxbot
  newTag: latest
configMapGenerator:
- name: kemadaxbot-configmap
  envs:
  - env/chatbot.env
secretGenerator:
- name: kemadaxbot-secret
  envs:
  - secret/chatbot.secret
