resources:
- kemadaxbot-service.yaml
- kemadaxbot-deployment.yaml
images:
- name: kemadax
  newName: ghcr.io/bproforigoss/kemadaxbot
  newTag: sha-b7db654
configMapGenerator:
- envs:
  - env/chatbot.env
  name: kemadaxbot-configmap
secretGenerator:
- envs:
  - secret/chatbot.secret
  name: kemadaxbot-secret
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 3
  name: kemadaxbot-deployment
