resources:
- kemadaxbot-service.yaml
- kemadaxbot-deployment.yaml
images:
- name: kemadax
  newName: ghcr.io/bproforigoss/kemadaxbot
  newTag: sha-df3220b
configMapGenerator:
- envs:
  - env/chatbot.env
  name: kemadaxbot-configmap
secretGenerator:
- envs:
  - secret/chatbot.secret
  name: kemadaxbot-secret
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
